language: python
python:
  - "3.6.9"

stages:
  - name: test
  - name: deploy

jobs:
  include: 
    - stage: test
      name: Unity Tests
      script: python manage.py test
    - stage: deploy
      name: Heroku Deploy
      script: /bin/true
      deploy:
        provider: heroku
        app: em-ecomm
        on: master
        run: "python manage.py migrate"